config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'salarys/index'

  get 'salarys/create'

  get 'relatorios/search', to: 'relatorios#search'
  post 'relatorios/search', to: 'relatorios#search'
  get 'relatorios/show', to: 'relatorios#show'

  devise_for :users
  resources :proponents
  resources :contacts
  resources :addresses
  root 'proponents#index'

  mount Sidekiq::Web => '/sidekiq'
  resources :salarys, only: %i[index create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  def search
    @proponents = if (params[:q] != '') && params[:q]
                    Proponent.where('salary = ?', params[:q])
                  else
                    # @proponents = Proponent.where.not(salary: [1045, 3000])
                    Proponent.all

                    # @proponents = Proponent.select('salary AS faixa_salarial_1').where(salary: 1045..3000)
                  end
  end

  def show
    @proponents_faixa_1 = Proponent.where(salary: 0..1045.00)
    @proponents_faixa_2 = Proponent.where(salary: 1045.01..2089.6)
    @proponents_faixa_3 = Proponent.where(salary: 2089.61..3134.4)
    @proponents_faixa_4 = Proponent.where(salary: 3134.41..6101.06)

    @quantidade_faixa_1 = Proponent.where(salary: 0..1045.00).count
    @quantidade_faixa_2 = Proponent.where(salary: 1045.01..2089.6).count
    @quantidade_faixa_3 = Proponent.where(salary: 2089.61..3134.4).count
    @quantidade_faixa_4 = Proponent.where(salary: 3134.41..6101.06).count

    @total_desconto_faixa_1 = Proponent.where(salary: 0..1045.00).sum(:discount)
    @total_desconto_faixa_2 = Proponent.where(salary: 1045.01..2089.6).sum(:discount)
    @total_desconto_faixa_3 = Proponent.where(salary: 2089.61..3134.4).sum(:discount)
    @total_desconto_faixa_4 = Proponent.where(salary: 3134.41..6101.06).sum(:discount)
  end
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/relatorios/search.html.erb
<div class="card-body">

	<h4 class="d-flex justify-content-between align-items-center mb-3">
	  <span class="text-muted">Consulta de Proponentes</span>
	</h4>

	<%= form_tag url: relatorios_search_path do %>
		<div class="form-row">
		  <div class="form-group col-md-12">
		    <%= label_tag :q, 'Salário:' %>
		  	<%= text_field_tag :q , params[:q] %>
		  </div>
		</div>

		<div class="actions text-center m-2">
      <%= submit_tag "Buscar", class:"btn btn-primary" %>

      <%= link_to relatorios_show_path, class: "btn btn-success" do %>
        RELATÓRIO
      <% end %>

    </div>

	<% end %>
	<h4 align="center">Resultados da busca</h4>

	<% if @proponents.present? %>
		<table class="table table-sm">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Nome</th>
		      <th scope="col">Salário base</th>
		      <th scope="col">Desconto</th>
		      <th class="text-center" scope="col">Ações</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @proponents.each do |proponent| %>
		    <tr>
		      <th scope="row"><%= proponent.id %></th>
		      <td><%= proponent.name %></td>
		      <td><%= number_to_currency(proponent.salary, unit: "R$ ", delimiter: ".", separator: ",")%></td>
		      <td><%= number_to_currency(proponent.discount, unit: "R$ ", delimiter: ".", separator: ",") %></td>
		     <% if proponent.amount_salary == 0 %>
		     	 <td align="center"><%= link_to 'Calcular', salarys_index_path(proponent: proponent.id), class:"btn btn-outline-dark" %></td>
		     <% else %>
		     	 <td align="center"><%= link_to 'Visualizar', salarys_index_path(proponent: proponent.id), class:"btn btn-outline-success" %></td>
		     <% end %>
		    </tr>
		    <% end %>
		  </tbody>
		</table>
	<% end %>
</div>

app/views/relatorios/show.html.erb
<h4 align="center" class="my-5"> Relatório de proponentes </h4>

<div class="row mb-3">
  <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Emissor:</label>
  <div class="col-sm-6">
  	<input type="email" value="<%= current_user.email %>" class="form-control form-control-sm" id="colFormLabelSm" readonly>
  </div>
  <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Data emissão:</label>
  <div class="col-sm-2">
  	<input type="email" id="date" class="form-control form-control-sm" id="colFormLabelSm" readonly>
  </div>
</div>

<hr>

<h5 class="my-3" align="center">Resultado - Salários por faixa salarial</h5>
<div class="table-responsive">
	<table class="table table-bordered">
	  <thead class="table-dark">
	    <tr>
	      <th scope="col">Faixa Salarial</th>
	      <th class="text-center" scope="col">Quantidades de proponetes</th>
	      <th class="text-center" scope="col">Total de descontos (R$)</th>
	    </tr>
	  </thead>
	  <tbody>
	    <tr>
	      <td>Salários até R$ 1045,00 </td>
	      <td align="center" ><%= @quantidade_faixa_1 %></td>
	      <td align="center"><%= @total_desconto_faixa_1 %></td>
	    </tr>
	    <% if @proponents_faixa_1.present? %>
		    <tr>
		    	<td colspan="4">
		        <table class="table table-sm">
	        		<thead class="table-dark">
						    <tr>
						    	<th scope="col">Id</th>
						      <th scope="col">Nome</th>
						      <th scope="col">Salário</th>
						      <th scope="col">Desconto</th>
						    </tr>
						  </thead>
						  <tbody>
						  	<% @proponents_faixa_1.each do |proponent| %>
						    <tr>
						      <th scope="row"><%= proponent.id %></th>
						      <td><%= proponent.name %></td>
						      <td><%= proponent.salary %></td>
						      <td><%= proponent.discount %></td>
						    </tr>
						    <% end %>
						  </tbody>
		        </table>
		      </td>
		    </tr>
	    <% end %>

	    <tr>
	      <td>Salários de R$ 1045,01 até R$ 2.089,60 </td>
	      <td align="center" ><%= @quantidade_faixa_2 %></td>
	      <td align="center"><%= @total_desconto_faixa_2 %></td>
	    </tr>
	    <% if @proponents_faixa_2.present? %>
	    <tr>
	    	<td colspan="4">
	        <table class="table table-sm">
	        	<thead class="table-dark">
					    <tr>
					    	<th scope="col">Id</th>
					      <th scope="col">Nome</th>
					      <th scope="col">Salário</th>
					      <th scope="col">Desconto</th>
					    </tr>
					  </thead>
					  <tbody>
					  	<% @proponents_faixa_2.each do |proponent| %>
					    <tr>
					      <th scope="row"><%= proponent.id %></th>
					      <td><%= proponent.name %></td>
					      <td><%= proponent.salary %></td>
					      <td><%= proponent.discount %></td>
					    </tr>
					    <% end %>
					  </tbody>
	        </table>
	      </td>
	    </tr>
			<% end %>
	    <tr>
	      <td>Salários de R$ 2.089,61 até R$ 3.134,40 </td>
	      <td align="center" ><%= @quantidade_faixa_3 %></td>
	      <td align="center"><%= @total_desconto_faixa_3 %></td>
	    </tr>
	    <% if @proponents_faixa_3.present? %>
	    <tr>
	    	<td colspan="4">
	        <table class="table table-sm">
	        	<thead class="table-dark">
					    <tr>
					    	<th scope="col">Id</th>
					      <th scope="col">Nome</th>
					      <th scope="col">Salário</th>
					      <th scope="col">Desconto</th>
					    </tr>
					  </thead>
					  <tbody>
					  	<% @proponents_faixa_3.each do |proponent| %>
					    <tr>
					      <th scope="row"><%= proponent.id %></th>
					      <td><%= proponent.name %></td>
					      <td><%= proponent.salary %></td>
					      <td><%= proponent.discount %></td>
					    </tr>
					    <% end %>
					  </tbody>
	        </table>
	      </td>
	    </tr>
			<% end %>
	    <tr>
	      <td>Salários de R$ 3.134,41 até R$ 6.101,06 </td>
	      <td align="center" ><%= @quantidade_faixa_4 %></td>
	      <td align="center"><%= @total_desconto_faixa_4 %></td>
	    </tr>
	    <% if @proponents_faixa_4.present? %>
	    <tr>
	    	<td colspan="4">
	        <table class="table table-sm">
	        	<thead class="table-dark">
					    <tr>
					    	<th scope="col">Id</th>
					      <th scope="col">Nome</th>
					      <th scope="col">Salário</th>
					      <th scope="col">Desconto</th>
					    </tr>
					  </thead>
					  <tbody>
					  	<% @proponents_faixa_4.each do |proponent| %>
					    <tr>
					      <th scope="row"><%= proponent.id %></th>
					      <td><%= proponent.name %></td>
					      <td><%= proponent.salary %></td>
					      <td><%= proponent.discount %></td>
					    </tr>
					    <% end %>
					  </tbody>
	        </table>
	      </td>
	    </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

<canvas id="myChart" width="200" height="50"></canvas>

<hr>

<script type="text/javascript">
	n =  new Date();
	y = n.getFullYear();
	m = n.getMonth() + 1;
	d = n.getDate();
	document.getElementById("date").value = m + "/" + d + "/" + y;


	var ctx = document.getElementById('myChart').getContext('2d');

	var myPieChart = new Chart(ctx, {
	    type: 'pie',
	    data: {
	    	datasets: [{
	    		data: [<%= @quantidade_faixa_1 %>, <%= @quantidade_faixa_2 %>, <%= @quantidade_faixa_3 %>, <%= @quantidade_faixa_4 %>],
	    		backgroundColor: [
		    		'rgba(255, 99, 132, 0.2)',
	          'rgba(54, 162, 235, 0.2)',
	          'rgba(255, 206, 86, 0.2)',
	          'rgba(75, 192, 192, 0.2)'
		    	]
	    	}],
	    	labels : [
	    		'Faixa 1',
	    		'Faixa 2',
	    		'Faixa 3',
	    		'Faixa 4'
	    	]
	    }
	});

	
</script>