config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'salarys/index'

  get 'salarys/create'

  get 'relatorios/search', to: 'relatorios#search'
  post 'relatorios/search', to: 'relatorios#search'
  get 'relatorios/show', to: 'relatorios#show'

  devise_for :users
  resources :proponents
  resources :contacts
  resources :addresses
  root 'proponents#index'

  mount Sidekiq::Web => '/sidekiq'
  resources :salarys, only: %i[index create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :proponent
  validates :kind, :value, presence: true
  validates :kind, inclusion: { in: %w[PESSOAL REFERENCIAL],
                                message: "%{value} não é válido, é esperado o valor 'PESSOAL' ou 'REFERENCIAL'" }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:kind, :value, :proponent_id)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(contact) do |f| %>

  <% if contact.errors.any? %>
    <div id="error_explanation">
      <% contact.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :kind %>
    <%= f.text_field :kind %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :proponent_id %>
    <%= f.text_field :proponent_id %>
  </div>

  <div class="actions">
    <%= f.button, :submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editar Contato</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contatos Cadastrados</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.kind %></td>
        <td><%= contact.value %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Contato', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @contact.value %>
</p>

<%= link_to 'Editar', edit_contact_path(@contact) %> |
<%= link_to 'Voltar', contacts_path %>