config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'salarys/index'

  get 'salarys/create'

  get 'relatorios/search', to: 'relatorios#search'
  post 'relatorios/search', to: 'relatorios#search'
  get 'relatorios/show', to: 'relatorios#show'

  devise_for :users
  resources :proponents
  resources :contacts
  resources :addresses
  root 'proponents#index'

  mount Sidekiq::Web => '/sidekiq'
  resources :salarys, only: %i[index create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[show edit update destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show; end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit; end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, warning: 'Endereço salvo com sucesso!' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, warning: 'Endereço atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = Address.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def address_params
    params.require(:address).permit(:street, :number, :district, :city, :state, :cep)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <% address.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :district %>
    <%= f.text_field :district %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Endereços</h1>

<table>
  <thead>
    <tr>
      <th>Logradouro</th>
      <th>Número</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Cep</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.street %></td>
        <td><%= address.number %></td>
        <td><%= address.district %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.cep %></td>
        <td><%= link_to 'Detalhar', address %></td>
        <td><%= link_to 'Editar', edit_address_path(address) %></td>
        <td><%= link_to 'Excluir', address, method: :delete, data: { confirm: 'Tem certeza que quer excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Endereço', new_address_path %>

app/views/addresses/new.html.erb
<h1>Novo endereço/h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p>
  <strong>Street:</strong>
  <%= @address.street %>
</p>

<p>
  <strong>Number:</strong>
  <%= @address.number %>
</p>

<p>
  <strong>District:</strong>
  <%= @address.district %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @address.cep %>
</p>

<%= link_to 'Editar', edit_address_path(@address) %> |
<%= link_to 'Voltar', addresses_path %>