config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'salarys/index'

  get 'salarys/create'

  get 'relatorios/search', to: 'relatorios#search'
  post 'relatorios/search', to: 'relatorios#search'
  get 'relatorios/show', to: 'relatorios#show'

  devise_for :users
  resources :proponents
  resources :contacts
  resources :addresses
  root 'proponents#index'

  mount Sidekiq::Web => '/sidekiq'
  resources :salarys, only: %i[index create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proponent.rb
class Proponent < ApplicationRecord
  belongs_to :address
  has_many :contacts

  validates :name, :cpf, :born_at, :salary, presence: true
  validates :name, length: { minimum: 12, maximum: 70 }
  validates :cpf, uniqueness: true
  validate :validator_cpf

  accepts_nested_attributes_for :contacts, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true

  def validator_cpf
    errors.add(:cpf, 'O CPF informado é inválido!') unless CPF.valid?(cpf)
  end
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  before_action :set_proponent, only: %i[show edit update destroy]

  # GET /proponents
  # GET /proponents.json
  def index
    @proponents = Proponent.all.order('id').page(params[:page]).per(5)
  end

  # GET /proponents/1
  # GET /proponents/1.json
  def show; end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
    @proponent.build_address
  end

  # GET /proponents/1/edit
  def edit; end

  # POST /proponents
  # POST /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to proponent_path, notice: 'Proponent was successfully created.' }
        # format.js
      else
        format.html { render :new }
        # format.js
      end
    end
  end

  # PATCH/PUT /proponents/1
  # PATCH/PUT /proponents/1.json
  def update
    respond_to do |format|
      if @proponent.update(proponent_params)
        format.html { redirect_to @proponent, notice: 'Proponent was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /proponents/1
  # DELETE /proponents/1.json
  def destroy
    @proponent.destroy
    respond_to do |format|
      format.html { redirect_to proponents_url, notice: 'Proponent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_proponent
    @proponent = Proponent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def proponent_params
    params.require(:proponent).permit(:name, :cpf, :born_at, :address_id, :salary, :discount,
                                      contacts_attributes: %i[
                                        id kind value _destroy
                                      ],
                                      address_attributes: %i[
                                        id street number district city state cep _destroy
                                      ])
  end
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/views/proponents/_address_fields.html.erb
<%= f.hidden_field :_destroy %>
<div class="field">
  <%= address_form.label :street, 'Logradouro:' %>
  <%= address_form.text_field :street, class: "form-control" %>
</div>

<div class="field">
  <%= address_form.label :number, 'Número:' %>
  <%= address_form.text_field :number, class: "form-control" %>
</div>

<div class="field">
  <%= address_form.label :district, 'Bairro:' %>
  <%= address_form.text_field :district, class: "form-control" %>
</div>

<div class="field">
  <%= address_form.label :cep, 'CEP:' %>
  <%= address_form.text_field :cep, class: "form-control" %>
</div>

<div class="field">
  <%= address_form.label :city, 'Cidade:' %>
  <%= address_form.text_field :city, class: "form-control" %>
</div>

<div class="field">
  <%= address_form.label :state, 'Estado:' %>
  <%= address_form.text_field :state, class: "form-control" %>
</div>
<div>
    <%= link_to "Remove", '#' %>
</div>

app/views/proponents/_form.html.erb
<%= simple_form_for proponent do |f| %>
  <%= f.error_notification %>

  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Dados Pessoais:</span>
  </h4>

  <div id="divForm" class="form-row">
    <div class="form-group col-md-8">
      <%= f.label :name, "Nome Completo:" %>
      <%= f.input_field :name, disabled: disabled, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :cpf, "CPF:" %>
      <%= f.input_field :cpf, class: 'form-control', disabled: disabled %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :born_at, "Data de nascimento:" %>
      <%= f.input_field :born_at, as: :date, html5: true, disabled: disabled, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-4">
      <%= f.label :salary, "Salário (R$):" %>
      <%= f.input_field :salary, class: 'form-control', disabled: disabled, id:"inputSalario", onchange: "modifiquei_alert()" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :discount, "Desconto:" %>
      <%= f.input_field :discount, id:'inputDesconto',  class: 'form-control', readonly: true %>
    </div>
  </div>

  <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Endereço:</span>
  </h4>
  
  <%= f.fields_for :address do |address_form| %>
    
    <div class="form-row">
      <div class="form-group col-md-8">
        <%= address_form.label :street, "Logradouro:" %>
        <%= address_form.input_field :street, disabled: disabled, class: 'form-control' %>
      </div>
      
      <div class="form-group col-md-4">
        <%= address_form.label :number, "Número:" %>
        <%= address_form.input_field :number, class: 'form-control', disabled: disabled %>
      </div>

      
    </div>

    <div class="form-row">
      <div class="form-group col-md-8">
        <%= address_form.label :district, "Bairro:" %>
        <%= address_form.input_field :district, disabled: disabled, class: 'form-control' %>
      </div>
      
      <div class="form-group col-md-4">
        <%= address_form.label :cep, "CEP:" %>
        <%= address_form.input_field :cep, class: 'form-control', disabled: disabled %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-8">
        <%= address_form.label :city, "Cidade:" %>
        <%= address_form.input_field :city, disabled: disabled, class: 'form-control' %>
      </div>
      
      <div class="form-group col-md-4">
        <%= address_form.label :state, "Estado:" %>
        <%= address_form.input_field :state, class: 'form-control', disabled: disabled %>
      </div>
    </div>
  <% end %>

  <% if !disabled %>
    <div class="actions text-center m-2">
      <%= f.button :submit, "Salvar", class:"btn btn-primary" %>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">

  function modifiquei_alert(){

    var salario = document.getElementById("inputSalario").value
    var valorRecolher = 0

    if(salario > 1045.00) {
      valorRecolher += 1045.00 * 0.075
      if(salario > 2089.6) {
        valorRecolher += (2089.6 - 1045) * 0.09
        if (salario > 3134.4) {
          valorRecolher += (3134.4 - 2089.6) * 0.12
          if (salario - 6101.06 > 0) {
            valorRecolher += (6101.06 - 3134.4) * 0.15
          } else {
            valorRecolher += (salario - 3134.4) * 0.15
          }
        } else {
          valorRecolher += (salario - 2089.6) * 0.12
        }
      } else {
        valorRecolher += (salario - 1045) * 0.09
      }
    } else {
      valorRecolher += salario * 0.075
    }
    document.getElementById("inputDesconto").value = valorRecolher
  }

</script>

app/views/proponents/create.js.erb
$("#divForm").html("<div class='alert alert-primary'><p>Proponente cadastrado com sucesso!</p></div>")

app/views/proponents/edit.html.erb
<h1>Editar Proponente</h1>

<%= render 'form', proponent: @proponent, disabled: false %>

<%= link_to 'Detalhar', @proponent %> |
<%= link_to 'Voltar', proponents_path %>

app/views/proponents/index.html.erb
<div class="row">
  <div class="col-12">

    <div class="clearfix">
      <h5 class="float-left">Proponentes Cadastrados</h5>
     
      <%= link_to new_proponent_path, class: "btn btn-primary float-right" do %>
        Novo Proponente
      <% end %>

      <%= link_to 'Consultar', relatorios_search_path, class:"btn btn-success float-right mx-2" %>

    </div>


    <br>
    <% if @proponents.present? %>
      
      <% @proponents.each do |proponent| %>
        
        <div id="accordion">
          <div class="card">
            <div class="card-header" id="heading<%= proponent.id %>" >
              <h5 class="mb-0">
                <button class="btn btn-link  text-dark dropdown-toggle" data-toggle="collapse" data-target="#collapse<%= proponent.id %>" aria-expanded="false" aria-controls="collapse<%= proponent.id %>"> 
                  <%= proponent.id %> - <%= proponent.name %>
                </button>
              </h5>
            </div>

            <div id="collapse<%= proponent.id %>" class="collapse" aria-labelledby="heading<%= proponent.id %>" data-parent="#accordion">
              <div class="card-body">
                <%= render 'form', proponent: proponent, disabled: true  %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @proponents %>

      
    <% else %>
      <div class="alert alert-warning">
        Nenhum registro encontrado!
      </div>
    <% end %>

  </div>
</div>

app/views/proponents/new.html.erb
<h1>Cadastro de proponente</h1>

<%= render 'form', proponent: @proponent, disabled: false %>

<%= link_to 'Voltar', proponents_path %>

app/views/proponents/show.html.erb
<div class="row">
  <div class="col-md-2 order-md-2 mb-4">
  </div>
  <div class="col-md-8 order-md-2 mb-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item active">Novo Proponente</li>
      <li class="list-group-item">Nome: <%= @proponent.name %></li>
      <li class="list-group-item">CPF: <%= @proponent.cpf %></li>
      <li class="list-group-item">Endereço: <%= @proponent.address.street + ", "+ @proponent.address.number + ", " + @proponent.address.district  %></li>
      <li class="list-group-item">Cidade: <%= @proponent.address.city %></li>
      <li class="list-group-item">Estado: <%= @proponent.address.state %></li>
      <li class="list-group-item">CEP: <%= @proponent.address.cep %></li>
      <li class="list-group-item">Data de Nascimento: <%= @proponent.born_at.strftime("%d/%m/%Y") %></li>
      <li class="list-group-item">Salário: <%= @proponent.salary %></li>
      <li class="list-group-item">Desconto: <%= @proponent.discount %></li>
    </ul>
    <div class="px-3 py-3 text-center">
      <%= link_to 'Editar', edit_proponent_path(@proponent), class:"m-2 btn btn-secondary" %>
      <%= link_to 'Voltar', proponents_path, class:"m-2 btn btn-secondary" %>
    </div>
  </div>
</div>